# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tornclient.models.faction_basic_response import FactionBasicResponse

class TestFactionBasicResponse(unittest.TestCase):
    """FactionBasicResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FactionBasicResponse:
        """Test FactionBasicResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FactionBasicResponse`
        """
        model = FactionBasicResponse()
        if include_optional:
            return FactionBasicResponse(
                basic = tornclient.models.faction_basic.FactionBasic(
                    id = 56, 
                    name = '', 
                    tag = '', 
                    tag_image = '', 
                    leader_id = 56, 
                    co_leader_id = 56, 
                    co_leader_id = 56, 
                    respect = 56, 
                    days_old = 56, 
                    capacity = 56, 
                    members = 56, 
                    is_enlisted = True, 
                    rank = tornclient.models.faction_rank.FactionRank(
                        level = 56, 
                        name = '', 
                        division = 56, 
                        position = 56, 
                        wins = 56, ), 
                    best_chain = 56, )
            )
        else:
            return FactionBasicResponse(
                basic = tornclient.models.faction_basic.FactionBasic(
                    id = 56, 
                    name = '', 
                    tag = '', 
                    tag_image = '', 
                    leader_id = 56, 
                    co_leader_id = 56, 
                    co_leader_id = 56, 
                    respect = 56, 
                    days_old = 56, 
                    capacity = 56, 
                    members = 56, 
                    is_enlisted = True, 
                    rank = tornclient.models.faction_rank.FactionRank(
                        level = 56, 
                        name = '', 
                        division = 56, 
                        position = 56, 
                        wins = 56, ), 
                    best_chain = 56, ),
        )
        """

    def testFactionBasicResponse(self):
        """Test FactionBasicResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
