# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tornclient.models.forum_get200_response import ForumGet200Response

class TestForumGet200Response(unittest.TestCase):
    """ForumGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForumGet200Response:
        """Test ForumGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForumGet200Response`
        """
        model = ForumGet200Response()
        if include_optional:
            return ForumGet200Response(
                categories = [
                    tornclient.models.forum_categories_response_categories_inner.ForumCategoriesResponse_categories_inner(
                        id = 56, 
                        title = '', 
                        acronym = '', 
                        threads = 56, )
                    ],
                threads = [
                    tornclient.models.forum_thread_base.ForumThreadBase(
                        id = 56, 
                        title = '', 
                        forum_id = 56, 
                        posts = 56, 
                        rating = 56, 
                        views = 56, 
                        author = tornclient.models.forum_thread_author.ForumThreadAuthor(
                            id = 56, 
                            username = '', 
                            karma = 56, ), 
                        last_poster = tornclient.models.forum_thread_author.ForumThreadAuthor(
                            id = 56, 
                            username = '', 
                            karma = 56, ), 
                        first_post_time = 56, 
                        last_post_time = 56, 
                        has_poll = True, 
                        is_locked = True, 
                        is_sticky = True, )
                    ],
                metadata = tornclient.models.request_metadata_with_links.RequestMetadataWithLinks(
                    links = tornclient.models.request_links.RequestLinks(
                        next = '', 
                        prev = '', ), ),
                thread = None,
                posts = [
                    tornclient.models.forum_post.ForumPost(
                        id = 56, 
                        thread_id = 56, 
                        author = tornclient.models.forum_thread_author.ForumThreadAuthor(
                            id = 56, 
                            username = '', 
                            karma = 56, ), 
                        is_legacy = True, 
                        is_topic = True, 
                        is_edited = True, 
                        is_pinned = True, 
                        created_time = 56, 
                        edited_by = 56, 
                        has_quote = True, 
                        quoted_post_id = 56, 
                        content = '', 
                        likes = 56, 
                        dislikes = 56, )
                    ],
                selections = [
                    'categories'
                    ],
                timestamp = 56
            )
        else:
            return ForumGet200Response(
                categories = [
                    tornclient.models.forum_categories_response_categories_inner.ForumCategoriesResponse_categories_inner(
                        id = 56, 
                        title = '', 
                        acronym = '', 
                        threads = 56, )
                    ],
                threads = [
                    tornclient.models.forum_thread_base.ForumThreadBase(
                        id = 56, 
                        title = '', 
                        forum_id = 56, 
                        posts = 56, 
                        rating = 56, 
                        views = 56, 
                        author = tornclient.models.forum_thread_author.ForumThreadAuthor(
                            id = 56, 
                            username = '', 
                            karma = 56, ), 
                        last_poster = tornclient.models.forum_thread_author.ForumThreadAuthor(
                            id = 56, 
                            username = '', 
                            karma = 56, ), 
                        first_post_time = 56, 
                        last_post_time = 56, 
                        has_poll = True, 
                        is_locked = True, 
                        is_sticky = True, )
                    ],
                metadata = tornclient.models.request_metadata_with_links.RequestMetadataWithLinks(
                    links = tornclient.models.request_links.RequestLinks(
                        next = '', 
                        prev = '', ), ),
                thread = None,
                posts = [
                    tornclient.models.forum_post.ForumPost(
                        id = 56, 
                        thread_id = 56, 
                        author = tornclient.models.forum_thread_author.ForumThreadAuthor(
                            id = 56, 
                            username = '', 
                            karma = 56, ), 
                        is_legacy = True, 
                        is_topic = True, 
                        is_edited = True, 
                        is_pinned = True, 
                        created_time = 56, 
                        edited_by = 56, 
                        has_quote = True, 
                        quoted_post_id = 56, 
                        content = '', 
                        likes = 56, 
                        dislikes = 56, )
                    ],
                selections = [
                    'categories'
                    ],
                timestamp = 56,
        )
        """

    def testForumGet200Response(self):
        """Test ForumGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
