# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tornclient.api.racing_api import RacingApi


class TestRacingApi(unittest.TestCase):
    """RacingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RacingApi()

    def tearDown(self) -> None:
        pass

    def test_racing_cars_get(self) -> None:
        """Test case for racing_cars_get

        Get cars and their racing stats
        """
        pass

    def test_racing_carupgrades_get(self) -> None:
        """Test case for racing_carupgrades_get

        Get all possible car upgrades
        """
        pass

    def test_racing_get(self) -> None:
        """Test case for racing_get

        Get any Racing selection
        """
        pass

    def test_racing_lookup_get(self) -> None:
        """Test case for racing_lookup_get

        Get all available racing selections
        """
        pass

    def test_racing_race_id_race_get(self) -> None:
        """Test case for racing_race_id_race_get

        Get specific race details
        """
        pass

    def test_racing_races_get(self) -> None:
        """Test case for racing_races_get

        Get races
        """
        pass

    def test_racing_timestamp_get(self) -> None:
        """Test case for racing_timestamp_get

        Get current server time
        """
        pass

    def test_racing_track_id_records_get(self) -> None:
        """Test case for racing_track_id_records_get

        Get track records
        """
        pass

    def test_racing_tracks_get(self) -> None:
        """Test case for racing_tracks_get

        Get race tracks and descriptions
        """
        pass


if __name__ == '__main__':
    unittest.main()
