# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tornclient.models.user_personal_stats_popular_personalstats import UserPersonalStatsPopularPersonalstats

class TestUserPersonalStatsPopularPersonalstats(unittest.TestCase):
    """UserPersonalStatsPopularPersonalstats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserPersonalStatsPopularPersonalstats:
        """Test UserPersonalStatsPopularPersonalstats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserPersonalStatsPopularPersonalstats`
        """
        model = UserPersonalStatsPopularPersonalstats()
        if include_optional:
            return UserPersonalStatsPopularPersonalstats(
                attacking = tornclient.models.personal_stats_attacking_popular_attacking.PersonalStatsAttackingPopular_attacking(
                    attacks = tornclient.models.personal_stats_attacking_popular_attacking_attacks.PersonalStatsAttackingPopular_attacking_attacks(
                        won = 56, 
                        lost = 56, 
                        stalemate = 56, 
                        assist = 56, ), 
                    defends = tornclient.models.personal_stats_attacking_popular_attacking_defends.PersonalStatsAttackingPopular_attacking_defends(
                        won = 56, 
                        lost = 56, 
                        stalemate = 56, ), 
                    elo = 56, 
                    escapes = tornclient.models.personal_stats_attacking_public_attacking_escapes.PersonalStatsAttackingPublic_attacking_escapes(
                        player = 56, 
                        foes = 56, ), 
                    killstreak = tornclient.models.personal_stats_attacking_public_attacking_killstreak.PersonalStatsAttackingPublic_attacking_killstreak(
                        best = 56, ), 
                    hits = tornclient.models.personal_stats_attacking_public_attacking_hits.PersonalStatsAttackingPublic_attacking_hits(
                        success = 56, 
                        miss = 56, 
                        critical = 56, 
                        one_hit_kills = 56, ), 
                    damage = tornclient.models.personal_stats_attacking_public_attacking_damage.PersonalStatsAttackingPublic_attacking_damage(
                        total = 56, 
                        best = 56, ), 
                    networth = tornclient.models.personal_stats_attacking_public_attacking_networth.PersonalStatsAttackingPublic_attacking_networth(
                        money_mugged = 56, 
                        largest_mug = 56, 
                        items_looted = 56, ), 
                    ammunition = tornclient.models.personal_stats_attacking_public_attacking_ammunition.PersonalStatsAttackingPublic_attacking_ammunition(
                        total = 56, 
                        special = 56, 
                        hollow_point = 56, 
                        tracer = 56, 
                        piercing = 56, 
                        incendiary = 56, ), 
                    faction = tornclient.models.personal_stats_attacking_popular_attacking_faction.PersonalStatsAttackingPopular_attacking_faction(
                        respect = 56, 
                        ranked_war_hits = 56, ), ),
                jobs = tornclient.models.personal_stats_jobs_public_jobs.PersonalStatsJobsPublic_jobs(
                    job_points_used = 56, 
                    trains_received = 56, ),
                hospital = tornclient.models.personal_stats_hospital_popular_hospital.PersonalStatsHospitalPopular_hospital(
                    medical_items_used = 56, 
                    reviving = tornclient.models.personal_stats_hospital_popular_hospital_reviving.PersonalStatsHospitalPopular_hospital_reviving(
                        skill = 56, 
                        revives = 56, ), ),
                crimes = tornclient.models.personal_stats_crimes_popular_crimes.PersonalStatsCrimesPopular_crimes(
                    total = 56, 
                    version = '', ),
                items = tornclient.models.personal_stats_items_popular_items.PersonalStatsItemsPopular_items(
                    found = tornclient.models.personal_stats_items_popular_items_found.PersonalStatsItemsPopular_items_found(
                        dump = 56, ), 
                    used = tornclient.models.personal_stats_items_items_used.PersonalStatsItems_items_used(
                        books = 56, 
                        boosters = 56, 
                        consumables = 56, 
                        candy = 56, 
                        alcohol = 56, 
                        energy_drinks = 56, 
                        stat_enhancers = 56, 
                        easter_eggs = 56, ), ),
                travel = tornclient.models.personal_stats_travel_popular_travel.PersonalStatsTravelPopular_travel(
                    total = 56, 
                    time_spent = 56, ),
                drugs = tornclient.models.personal_stats_drugs_drugs.PersonalStatsDrugs_drugs(
                    cannabis = 56, 
                    ecstasy = 56, 
                    ketamine = 56, 
                    lsd = 56, 
                    opium = 56, 
                    pcp = 56, 
                    shrooms = 56, 
                    speed = 56, 
                    vicodin = 56, 
                    xanax = 56, 
                    total = 56, 
                    overdoses = 56, 
                    rehabilitations = tornclient.models.personal_stats_drugs_drugs_rehabilitations.PersonalStatsDrugs_drugs_rehabilitations(
                        amount = 56, 
                        fees = 56, ), ),
                networth = tornclient.models.personal_stats_networth_public_networth.PersonalStatsNetworthPublic_networth(
                    total = 56, ),
                other = tornclient.models.personal_stats_other_popular_other.PersonalStatsOtherPopular_other(
                    activity = tornclient.models.personal_stats_other_other_activity.PersonalStatsOther_other_activity(
                        time = 56, 
                        streak = tornclient.models.personal_stats_other_other_activity_streak.PersonalStatsOther_other_activity_streak(
                            best = 56, 
                            current = 56, ), ), 
                    awards = 56, 
                    merits_bought = 56, 
                    refills = tornclient.models.personal_stats_other_popular_other_refills.PersonalStatsOtherPopular_other_refills(
                        energy = 56, 
                        nerve = 56, ), 
                    donator_days = 56, 
                    ranked_war_wins = 56, )
            )
        else:
            return UserPersonalStatsPopularPersonalstats(
                attacking = tornclient.models.personal_stats_attacking_popular_attacking.PersonalStatsAttackingPopular_attacking(
                    attacks = tornclient.models.personal_stats_attacking_popular_attacking_attacks.PersonalStatsAttackingPopular_attacking_attacks(
                        won = 56, 
                        lost = 56, 
                        stalemate = 56, 
                        assist = 56, ), 
                    defends = tornclient.models.personal_stats_attacking_popular_attacking_defends.PersonalStatsAttackingPopular_attacking_defends(
                        won = 56, 
                        lost = 56, 
                        stalemate = 56, ), 
                    elo = 56, 
                    escapes = tornclient.models.personal_stats_attacking_public_attacking_escapes.PersonalStatsAttackingPublic_attacking_escapes(
                        player = 56, 
                        foes = 56, ), 
                    killstreak = tornclient.models.personal_stats_attacking_public_attacking_killstreak.PersonalStatsAttackingPublic_attacking_killstreak(
                        best = 56, ), 
                    hits = tornclient.models.personal_stats_attacking_public_attacking_hits.PersonalStatsAttackingPublic_attacking_hits(
                        success = 56, 
                        miss = 56, 
                        critical = 56, 
                        one_hit_kills = 56, ), 
                    damage = tornclient.models.personal_stats_attacking_public_attacking_damage.PersonalStatsAttackingPublic_attacking_damage(
                        total = 56, 
                        best = 56, ), 
                    networth = tornclient.models.personal_stats_attacking_public_attacking_networth.PersonalStatsAttackingPublic_attacking_networth(
                        money_mugged = 56, 
                        largest_mug = 56, 
                        items_looted = 56, ), 
                    ammunition = tornclient.models.personal_stats_attacking_public_attacking_ammunition.PersonalStatsAttackingPublic_attacking_ammunition(
                        total = 56, 
                        special = 56, 
                        hollow_point = 56, 
                        tracer = 56, 
                        piercing = 56, 
                        incendiary = 56, ), 
                    faction = tornclient.models.personal_stats_attacking_popular_attacking_faction.PersonalStatsAttackingPopular_attacking_faction(
                        respect = 56, 
                        ranked_war_hits = 56, ), ),
                jobs = tornclient.models.personal_stats_jobs_public_jobs.PersonalStatsJobsPublic_jobs(
                    job_points_used = 56, 
                    trains_received = 56, ),
                hospital = tornclient.models.personal_stats_hospital_popular_hospital.PersonalStatsHospitalPopular_hospital(
                    medical_items_used = 56, 
                    reviving = tornclient.models.personal_stats_hospital_popular_hospital_reviving.PersonalStatsHospitalPopular_hospital_reviving(
                        skill = 56, 
                        revives = 56, ), ),
                crimes = tornclient.models.personal_stats_crimes_popular_crimes.PersonalStatsCrimesPopular_crimes(
                    total = 56, 
                    version = '', ),
                items = tornclient.models.personal_stats_items_popular_items.PersonalStatsItemsPopular_items(
                    found = tornclient.models.personal_stats_items_popular_items_found.PersonalStatsItemsPopular_items_found(
                        dump = 56, ), 
                    used = tornclient.models.personal_stats_items_items_used.PersonalStatsItems_items_used(
                        books = 56, 
                        boosters = 56, 
                        consumables = 56, 
                        candy = 56, 
                        alcohol = 56, 
                        energy_drinks = 56, 
                        stat_enhancers = 56, 
                        easter_eggs = 56, ), ),
                travel = tornclient.models.personal_stats_travel_popular_travel.PersonalStatsTravelPopular_travel(
                    total = 56, 
                    time_spent = 56, ),
                drugs = tornclient.models.personal_stats_drugs_drugs.PersonalStatsDrugs_drugs(
                    cannabis = 56, 
                    ecstasy = 56, 
                    ketamine = 56, 
                    lsd = 56, 
                    opium = 56, 
                    pcp = 56, 
                    shrooms = 56, 
                    speed = 56, 
                    vicodin = 56, 
                    xanax = 56, 
                    total = 56, 
                    overdoses = 56, 
                    rehabilitations = tornclient.models.personal_stats_drugs_drugs_rehabilitations.PersonalStatsDrugs_drugs_rehabilitations(
                        amount = 56, 
                        fees = 56, ), ),
                networth = tornclient.models.personal_stats_networth_public_networth.PersonalStatsNetworthPublic_networth(
                    total = 56, ),
                other = tornclient.models.personal_stats_other_popular_other.PersonalStatsOtherPopular_other(
                    activity = tornclient.models.personal_stats_other_other_activity.PersonalStatsOther_other_activity(
                        time = 56, 
                        streak = tornclient.models.personal_stats_other_other_activity_streak.PersonalStatsOther_other_activity_streak(
                            best = 56, 
                            current = 56, ), ), 
                    awards = 56, 
                    merits_bought = 56, 
                    refills = tornclient.models.personal_stats_other_popular_other_refills.PersonalStatsOtherPopular_other_refills(
                        energy = 56, 
                        nerve = 56, ), 
                    donator_days = 56, 
                    ranked_war_wins = 56, ),
        )
        """

    def testUserPersonalStatsPopularPersonalstats(self):
        """Test UserPersonalStatsPopularPersonalstats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
