# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tornclient.models.torn_calendar_response import TornCalendarResponse

class TestTornCalendarResponse(unittest.TestCase):
    """TornCalendarResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TornCalendarResponse:
        """Test TornCalendarResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TornCalendarResponse`
        """
        model = TornCalendarResponse()
        if include_optional:
            return TornCalendarResponse(
                calendar = tornclient.models.torn_calendar_response_calendar.TornCalendarResponse_calendar(
                    competitions = [
                        tornclient.models.torn_calendar_activity.TornCalendarActivity(
                            title = '', 
                            description = '', 
                            start = 56, 
                            end = 56, )
                        ], 
                    events = [
                        tornclient.models.torn_calendar_activity.TornCalendarActivity(
                            title = '', 
                            description = '', 
                            start = 56, 
                            end = 56, )
                        ], )
            )
        else:
            return TornCalendarResponse(
                calendar = tornclient.models.torn_calendar_response_calendar.TornCalendarResponse_calendar(
                    competitions = [
                        tornclient.models.torn_calendar_activity.TornCalendarActivity(
                            title = '', 
                            description = '', 
                            start = 56, 
                            end = 56, )
                        ], 
                    events = [
                        tornclient.models.torn_calendar_activity.TornCalendarActivity(
                            title = '', 
                            description = '', 
                            start = 56, 
                            end = 56, )
                        ], ),
        )
        """

    def testTornCalendarResponse(self):
        """Test TornCalendarResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
