# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tornclient.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_user_attacks_get(self) -> None:
        """Test case for user_attacks_get

        Get your detailed attacks
        """
        pass

    def test_user_attacksfull_get(self) -> None:
        """Test case for user_attacksfull_get

        Get your simplified attacks
        """
        pass

    def test_user_bounties_get(self) -> None:
        """Test case for user_bounties_get

        Get bounties placed on you
        """
        pass

    def test_user_calendar_get(self) -> None:
        """Test case for user_calendar_get

        Get your competition's event start time
        """
        pass

    def test_user_crime_id_crimes_get(self) -> None:
        """Test case for user_crime_id_crimes_get

        Get your crime statistics
        """
        pass

    def test_user_education_get(self) -> None:
        """Test case for user_education_get

        Get your education information
        """
        pass

    def test_user_enlistedcars_get(self) -> None:
        """Test case for user_enlistedcars_get

        Get user enlisted cars
        """
        pass

    def test_user_factionbalance_get(self) -> None:
        """Test case for user_factionbalance_get

        Get your current faction balance
        """
        pass

    def test_user_forumfeed_get(self) -> None:
        """Test case for user_forumfeed_get

        Get updates on your threads and posts
        """
        pass

    def test_user_forumfriends_get(self) -> None:
        """Test case for user_forumfriends_get

        Get updates on your friends' activity
        """
        pass

    def test_user_forumposts_get(self) -> None:
        """Test case for user_forumposts_get

        Get your posts
        """
        pass

    def test_user_forumsubscribedthreads_get(self) -> None:
        """Test case for user_forumsubscribedthreads_get

        Get updates on threads you subscribed to
        """
        pass

    def test_user_forumthreads_get(self) -> None:
        """Test case for user_forumthreads_get

        Get your threads
        """
        pass

    def test_user_get(self) -> None:
        """Test case for user_get

        Get any User selection
        """
        pass

    def test_user_hof_get(self) -> None:
        """Test case for user_hof_get

        Get your hall of fame rankings
        """
        pass

    def test_user_id_bounties_get(self) -> None:
        """Test case for user_id_bounties_get

        Get bounties placed on a specific user
        """
        pass

    def test_user_id_forumposts_get(self) -> None:
        """Test case for user_id_forumposts_get

        Get posts for a specific player
        """
        pass

    def test_user_id_forumthreads_get(self) -> None:
        """Test case for user_id_forumthreads_get

        Get threads for a specific player
        """
        pass

    def test_user_id_hof_get(self) -> None:
        """Test case for user_id_hof_get

        Get hall of fame rankings for a specific player
        """
        pass

    def test_user_id_personalstats_get(self) -> None:
        """Test case for user_id_personalstats_get

        Get a player's personal stats
        """
        pass

    def test_user_itemmarket_get(self) -> None:
        """Test case for user_itemmarket_get

        Get your item market listings for a specific item
        """
        pass

    def test_user_jobranks_get(self) -> None:
        """Test case for user_jobranks_get

        Get your starter job positions
        """
        pass

    def test_user_list_get(self) -> None:
        """Test case for user_list_get

        Get your friends, enemies or targets list
        """
        pass

    def test_user_lookup_get(self) -> None:
        """Test case for user_lookup_get

        Get all available user selections
        """
        pass

    def test_user_organizedcrime_get(self) -> None:
        """Test case for user_organizedcrime_get

        Get your current ongoing organized crime
        """
        pass

    def test_user_personalstats_get(self) -> None:
        """Test case for user_personalstats_get

        Get your personal stats
        """
        pass

    def test_user_races_get(self) -> None:
        """Test case for user_races_get

        Get user races
        """
        pass

    def test_user_revives_full_get(self) -> None:
        """Test case for user_revives_full_get

        Get your simplified revives
        """
        pass

    def test_user_revives_get(self) -> None:
        """Test case for user_revives_get

        Get your detailed revives
        """
        pass

    def test_user_timestamp_get(self) -> None:
        """Test case for user_timestamp_get

        Get current server time
        """
        pass


if __name__ == '__main__':
    unittest.main()
