# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tornclient.api.torn_api import TornApi


class TestTornApi(unittest.TestCase):
    """TornApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TornApi()

    def tearDown(self) -> None:
        pass

    def test_torn_attacklog_get(self) -> None:
        """Test case for torn_attacklog_get

        Get attack log details
        """
        pass

    def test_torn_bounties_get(self) -> None:
        """Test case for torn_bounties_get

        Get bounties
        """
        pass

    def test_torn_calendar_get(self) -> None:
        """Test case for torn_calendar_get

        Get calendar information
        """
        pass

    def test_torn_crime_id_subcrimes_get(self) -> None:
        """Test case for torn_crime_id_subcrimes_get

        Get Subcrimes information
        """
        pass

    def test_torn_crimes_get(self) -> None:
        """Test case for torn_crimes_get

        Get crimes information
        """
        pass

    def test_torn_education_get(self) -> None:
        """Test case for torn_education_get

        Get education information
        """
        pass

    def test_torn_factionhof_get(self) -> None:
        """Test case for torn_factionhof_get

        Get faction hall of fame positions for a specific category
        """
        pass

    def test_torn_factiontree_get(self) -> None:
        """Test case for torn_factiontree_get

        Get full faction tree
        """
        pass

    def test_torn_get(self) -> None:
        """Test case for torn_get

        Get any Torn selection
        """
        pass

    def test_torn_hof_get(self) -> None:
        """Test case for torn_hof_get

        Get player hall of fame positions for a specific category
        """
        pass

    def test_torn_ids_items_get(self) -> None:
        """Test case for torn_ids_items_get

        Get information about items
        """
        pass

    def test_torn_itemammo_get(self) -> None:
        """Test case for torn_itemammo_get

        Get information about ammo
        """
        pass

    def test_torn_itemmods_get(self) -> None:
        """Test case for torn_itemmods_get

        Get information about weapon upgrades
        """
        pass

    def test_torn_items_get(self) -> None:
        """Test case for torn_items_get

        Get information about items
        """
        pass

    def test_torn_log_category_id_logtypes_get(self) -> None:
        """Test case for torn_log_category_id_logtypes_get

        Get available log ids for a specific log category
        """
        pass

    def test_torn_logcategories_get(self) -> None:
        """Test case for torn_logcategories_get

        Get available log categories
        """
        pass

    def test_torn_logtypes_get(self) -> None:
        """Test case for torn_logtypes_get

        Get all available log ids
        """
        pass

    def test_torn_lookup_get(self) -> None:
        """Test case for torn_lookup_get

        Get all available torn selections
        """
        pass

    def test_torn_territory_get(self) -> None:
        """Test case for torn_territory_get

        Get territory details
        """
        pass

    def test_torn_territory_ids_territory_get(self) -> None:
        """Test case for torn_territory_ids_territory_get

        Get territory details
        """
        pass

    def test_torn_timestamp_get(self) -> None:
        """Test case for torn_timestamp_get

        Get current server time
        """
        pass


if __name__ == '__main__':
    unittest.main()
