# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tornclient.models.forum_threads_response import ForumThreadsResponse

class TestForumThreadsResponse(unittest.TestCase):
    """ForumThreadsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForumThreadsResponse:
        """Test ForumThreadsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForumThreadsResponse`
        """
        model = ForumThreadsResponse()
        if include_optional:
            return ForumThreadsResponse(
                threads = [
                    tornclient.models.forum_thread_base.ForumThreadBase(
                        id = 56, 
                        title = '', 
                        forum_id = 56, 
                        posts = 56, 
                        rating = 56, 
                        views = 56, 
                        author = tornclient.models.forum_thread_author.ForumThreadAuthor(
                            id = 56, 
                            username = '', 
                            karma = 56, ), 
                        last_poster = tornclient.models.forum_thread_author.ForumThreadAuthor(
                            id = 56, 
                            username = '', 
                            karma = 56, ), 
                        first_post_time = 56, 
                        last_post_time = 56, 
                        has_poll = True, 
                        is_locked = True, 
                        is_sticky = True, )
                    ],
                metadata = tornclient.models.request_metadata_with_links.RequestMetadataWithLinks(
                    links = tornclient.models.request_links.RequestLinks(
                        next = '', 
                        prev = '', ), )
            )
        else:
            return ForumThreadsResponse(
                threads = [
                    tornclient.models.forum_thread_base.ForumThreadBase(
                        id = 56, 
                        title = '', 
                        forum_id = 56, 
                        posts = 56, 
                        rating = 56, 
                        views = 56, 
                        author = tornclient.models.forum_thread_author.ForumThreadAuthor(
                            id = 56, 
                            username = '', 
                            karma = 56, ), 
                        last_poster = tornclient.models.forum_thread_author.ForumThreadAuthor(
                            id = 56, 
                            username = '', 
                            karma = 56, ), 
                        first_post_time = 56, 
                        last_post_time = 56, 
                        has_poll = True, 
                        is_locked = True, 
                        is_sticky = True, )
                    ],
                metadata = tornclient.models.request_metadata_with_links.RequestMetadataWithLinks(
                    links = tornclient.models.request_links.RequestLinks(
                        next = '', 
                        prev = '', ), ),
        )
        """

    def testForumThreadsResponse(self):
        """Test ForumThreadsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
