# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tornclient.models.torn_hof_response import TornHofResponse

class TestTornHofResponse(unittest.TestCase):
    """TornHofResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TornHofResponse:
        """Test TornHofResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TornHofResponse`
        """
        model = TornHofResponse()
        if include_optional:
            return TornHofResponse(
                hof = [
                    tornclient.models.torn_hof.TornHof(
                        id = 56, 
                        username = '', 
                        faction_id = 56, 
                        level = 56, 
                        last_action = 56, 
                        rank_name = '', 
                        rank_number = 56, 
                        position = 56, 
                        signed_up = 56, 
                        age_in_days = 56, 
                        value = null, 
                        rank = '', )
                    ],
                metadata = tornclient.models.request_metadata_with_links.RequestMetadataWithLinks(
                    links = tornclient.models.request_links.RequestLinks(
                        next = '', 
                        prev = '', ), )
            )
        else:
            return TornHofResponse(
                hof = [
                    tornclient.models.torn_hof.TornHof(
                        id = 56, 
                        username = '', 
                        faction_id = 56, 
                        level = 56, 
                        last_action = 56, 
                        rank_name = '', 
                        rank_number = 56, 
                        position = 56, 
                        signed_up = 56, 
                        age_in_days = 56, 
                        value = null, 
                        rank = '', )
                    ],
                metadata = tornclient.models.request_metadata_with_links.RequestMetadataWithLinks(
                    links = tornclient.models.request_links.RequestLinks(
                        next = '', 
                        prev = '', ), ),
        )
        """

    def testTornHofResponse(self):
        """Test TornHofResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
