# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tornclient.models.forum_subscribed_thread_posts_count import ForumSubscribedThreadPostsCount

class TestForumSubscribedThreadPostsCount(unittest.TestCase):
    """ForumSubscribedThreadPostsCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForumSubscribedThreadPostsCount:
        """Test ForumSubscribedThreadPostsCount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForumSubscribedThreadPostsCount`
        """
        model = ForumSubscribedThreadPostsCount()
        if include_optional:
            return ForumSubscribedThreadPostsCount(
                new = 56,
                total = 56
            )
        else:
            return ForumSubscribedThreadPostsCount(
                new = 56,
                total = 56,
        )
        """

    def testForumSubscribedThreadPostsCount(self):
        """Test ForumSubscribedThreadPostsCount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
