# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tornclient.models.personal_stats_crimes_v2_offenses import PersonalStatsCrimesV2Offenses

class TestPersonalStatsCrimesV2Offenses(unittest.TestCase):
    """PersonalStatsCrimesV2Offenses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PersonalStatsCrimesV2Offenses:
        """Test PersonalStatsCrimesV2Offenses
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PersonalStatsCrimesV2Offenses`
        """
        model = PersonalStatsCrimesV2Offenses()
        if include_optional:
            return PersonalStatsCrimesV2Offenses(
                vandalism = 56,
                fraud = 56,
                theft = 56,
                counterfeiting = 56,
                illicit_services = 56,
                cybercrime = 56,
                extortion = 56,
                illegal_production = 56,
                organized_crimes = 56,
                total = 56
            )
        else:
            return PersonalStatsCrimesV2Offenses(
                vandalism = 56,
                fraud = 56,
                theft = 56,
                counterfeiting = 56,
                illicit_services = 56,
                cybercrime = 56,
                extortion = 56,
                illegal_production = 56,
                organized_crimes = 56,
                total = 56,
        )
        """

    def testPersonalStatsCrimesV2Offenses(self):
        """Test PersonalStatsCrimesV2Offenses"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
