# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from tornclient.models.market_get200_response import MarketGet200Response
from tornclient.models.market_item_market_response import MarketItemMarketResponse
from tornclient.models.market_lookup_response import MarketLookupResponse
from tornclient.models.market_selection_name import MarketSelectionName
from tornclient.models.timestamp_response import TimestampResponse
from tornclient.models.weapon_bonus_enum import WeaponBonusEnum

from tornclient.api_client import ApiClient, RequestSerialized
from tornclient.api_response import ApiResponse
from tornclient.rest import RESTResponseType


class MarketApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def market_get(
        self,
        selections: Annotated[Optional[List[MarketSelectionName]], Field(description="Selection names")] = None,
        id: Annotated[Optional[StrictStr], Field(description="selection id")] = None,
        bonus: Annotated[Optional[WeaponBonusEnum], Field(description="Used to filter weapons with a specific bonus")] = None,
        cat: Annotated[Optional[StrictStr], Field(description="Selection category")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Direction to sort rows in")] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> MarketGet200Response:
        """Get any Market selection

        Requires public access key. <br>Choose one or more selections (comma separated).

        :param selections: Selection names
        :type selections: List[MarketSelectionName]
        :param id: selection id
        :type id: str
        :param bonus: Used to filter weapons with a specific bonus
        :type bonus: WeaponBonusEnum
        :param cat: Selection category
        :type cat: str
        :param sort: Direction to sort rows in
        :type sort: str
        :param offset:
        :type offset: int
        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_get_serialize(
            selections=selections,
            id=id,
            bonus=bonus,
            cat=cat,
            sort=sort,
            offset=offset,
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MarketGet200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def market_get_with_http_info(
        self,
        selections: Annotated[Optional[List[MarketSelectionName]], Field(description="Selection names")] = None,
        id: Annotated[Optional[StrictStr], Field(description="selection id")] = None,
        bonus: Annotated[Optional[WeaponBonusEnum], Field(description="Used to filter weapons with a specific bonus")] = None,
        cat: Annotated[Optional[StrictStr], Field(description="Selection category")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Direction to sort rows in")] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[MarketGet200Response]:
        """Get any Market selection

        Requires public access key. <br>Choose one or more selections (comma separated).

        :param selections: Selection names
        :type selections: List[MarketSelectionName]
        :param id: selection id
        :type id: str
        :param bonus: Used to filter weapons with a specific bonus
        :type bonus: WeaponBonusEnum
        :param cat: Selection category
        :type cat: str
        :param sort: Direction to sort rows in
        :type sort: str
        :param offset:
        :type offset: int
        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_get_serialize(
            selections=selections,
            id=id,
            bonus=bonus,
            cat=cat,
            sort=sort,
            offset=offset,
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MarketGet200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def market_get_without_preload_content(
        self,
        selections: Annotated[Optional[List[MarketSelectionName]], Field(description="Selection names")] = None,
        id: Annotated[Optional[StrictStr], Field(description="selection id")] = None,
        bonus: Annotated[Optional[WeaponBonusEnum], Field(description="Used to filter weapons with a specific bonus")] = None,
        cat: Annotated[Optional[StrictStr], Field(description="Selection category")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Direction to sort rows in")] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get any Market selection

        Requires public access key. <br>Choose one or more selections (comma separated).

        :param selections: Selection names
        :type selections: List[MarketSelectionName]
        :param id: selection id
        :type id: str
        :param bonus: Used to filter weapons with a specific bonus
        :type bonus: WeaponBonusEnum
        :param cat: Selection category
        :type cat: str
        :param sort: Direction to sort rows in
        :type sort: str
        :param offset:
        :type offset: int
        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_get_serialize(
            selections=selections,
            id=id,
            bonus=bonus,
            cat=cat,
            sort=sort,
            offset=offset,
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MarketGet200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _market_get_serialize(
        self,
        selections,
        id,
        bonus,
        cat,
        sort,
        offset,
        timestamp,
        comment,
        key,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'selections': 'csv',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if selections is not None:
            
            _query_params.append(('selections', selections))
            
        if id is not None:
            
            _query_params.append(('id', id))
            
        if bonus is not None:
            
            _query_params.append(('bonus', bonus.value))
            
        if cat is not None:
            
            _query_params.append(('cat', cat))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if timestamp is not None:
            
            _query_params.append(('timestamp', timestamp))
            
        if comment is not None:
            
            _query_params.append(('comment', comment))
            
        if key is not None:
            
            _query_params.append(('key', key))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'api_key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/market',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def market_id_itemmarket_get(
        self,
        id: Annotated[StrictInt, Field(description="Item id")],
        bonus: Annotated[Optional[WeaponBonusEnum], Field(description="Used to filter weapons with a specific bonus.")] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> MarketItemMarketResponse:
        """Get item market listings

        Requires public access key. <br>

        :param id: Item id (required)
        :type id: int
        :param bonus: Used to filter weapons with a specific bonus.
        :type bonus: WeaponBonusEnum
        :param offset:
        :type offset: int
        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_id_itemmarket_get_serialize(
            id=id,
            bonus=bonus,
            offset=offset,
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MarketItemMarketResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def market_id_itemmarket_get_with_http_info(
        self,
        id: Annotated[StrictInt, Field(description="Item id")],
        bonus: Annotated[Optional[WeaponBonusEnum], Field(description="Used to filter weapons with a specific bonus.")] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[MarketItemMarketResponse]:
        """Get item market listings

        Requires public access key. <br>

        :param id: Item id (required)
        :type id: int
        :param bonus: Used to filter weapons with a specific bonus.
        :type bonus: WeaponBonusEnum
        :param offset:
        :type offset: int
        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_id_itemmarket_get_serialize(
            id=id,
            bonus=bonus,
            offset=offset,
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MarketItemMarketResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def market_id_itemmarket_get_without_preload_content(
        self,
        id: Annotated[StrictInt, Field(description="Item id")],
        bonus: Annotated[Optional[WeaponBonusEnum], Field(description="Used to filter weapons with a specific bonus.")] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get item market listings

        Requires public access key. <br>

        :param id: Item id (required)
        :type id: int
        :param bonus: Used to filter weapons with a specific bonus.
        :type bonus: WeaponBonusEnum
        :param offset:
        :type offset: int
        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_id_itemmarket_get_serialize(
            id=id,
            bonus=bonus,
            offset=offset,
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MarketItemMarketResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _market_id_itemmarket_get_serialize(
        self,
        id,
        bonus,
        offset,
        timestamp,
        comment,
        key,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        if bonus is not None:
            
            _query_params.append(('bonus', bonus.value))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if timestamp is not None:
            
            _query_params.append(('timestamp', timestamp))
            
        if comment is not None:
            
            _query_params.append(('comment', comment))
            
        if key is not None:
            
            _query_params.append(('key', key))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'api_key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/market/{id}/itemmarket',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def market_lookup_get(
        self,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> MarketLookupResponse:
        """Get all available market selections

        Requires public access key. <br>

        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_lookup_get_serialize(
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MarketLookupResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def market_lookup_get_with_http_info(
        self,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[MarketLookupResponse]:
        """Get all available market selections

        Requires public access key. <br>

        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_lookup_get_serialize(
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MarketLookupResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def market_lookup_get_without_preload_content(
        self,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get all available market selections

        Requires public access key. <br>

        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_lookup_get_serialize(
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MarketLookupResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _market_lookup_get_serialize(
        self,
        timestamp,
        comment,
        key,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if timestamp is not None:
            
            _query_params.append(('timestamp', timestamp))
            
        if comment is not None:
            
            _query_params.append(('comment', comment))
            
        if key is not None:
            
            _query_params.append(('key', key))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'api_key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/market/lookup',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def market_timestamp_get(
        self,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> TimestampResponse:
        """Get current server time

        Requires public access key. <br>

        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_timestamp_get_serialize(
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TimestampResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def market_timestamp_get_with_http_info(
        self,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[TimestampResponse]:
        """Get current server time

        Requires public access key. <br>

        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_timestamp_get_serialize(
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TimestampResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def market_timestamp_get_without_preload_content(
        self,
        timestamp: Annotated[Optional[StrictStr], Field(description="Timestamp to bypass cache")] = None,
        comment: Annotated[Optional[StrictStr], Field(description="Comment for your tool/service/bot/website to be visible in the logs.")] = None,
        key: Annotated[Optional[StrictStr], Field(description="API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get current server time

        Requires public access key. <br>

        :param timestamp: Timestamp to bypass cache
        :type timestamp: str
        :param comment: Comment for your tool/service/bot/website to be visible in the logs.
        :type comment: str
        :param key: API key (Public).<br>It's not required to use this parameter when passing the API key via the Authorization header.
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._market_timestamp_get_serialize(
            timestamp=timestamp,
            comment=comment,
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TimestampResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _market_timestamp_get_serialize(
        self,
        timestamp,
        comment,
        key,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if timestamp is not None:
            
            _query_params.append(('timestamp', timestamp))
            
        if comment is not None:
            
            _query_params.append(('comment', comment))
            
        if key is not None:
            
            _query_params.append(('key', key))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'api_key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/market/timestamp',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


