# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from tornclient.models.faction_territory_enum import FactionTerritoryEnum
from tornclient.models.torn_racket import TornRacket
from tornclient.models.torn_territory_coordinates import TornTerritoryCoordinates
from typing import Optional, Set
from typing_extensions import Self

class FactionTerritory(BaseModel):
    """
    FactionTerritory
    """ # noqa: E501
    id: FactionTerritoryEnum
    acquired_at: StrictInt
    sector: StrictInt
    size: StrictInt
    density: StrictInt
    slots: StrictInt
    respect: StrictInt
    coordinates: TornTerritoryCoordinates
    racket: Optional[TornRacket]
    __properties: ClassVar[List[str]] = ["id", "acquired_at", "sector", "size", "density", "slots", "respect", "coordinates", "racket"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FactionTerritory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coordinates
        if self.coordinates:
            _dict['coordinates'] = self.coordinates.to_dict()
        # override the default output from pydantic by calling `to_dict()` of racket
        if self.racket:
            _dict['racket'] = self.racket.to_dict()
        # set to None if racket (nullable) is None
        # and model_fields_set contains the field
        if self.racket is None and "racket" in self.model_fields_set:
            _dict['racket'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FactionTerritory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "acquired_at": obj.get("acquired_at"),
            "sector": obj.get("sector"),
            "size": obj.get("size"),
            "density": obj.get("density"),
            "slots": obj.get("slots"),
            "respect": obj.get("respect"),
            "coordinates": TornTerritoryCoordinates.from_dict(obj["coordinates"]) if obj.get("coordinates") is not None else None,
            "racket": TornRacket.from_dict(obj["racket"]) if obj.get("racket") is not None else None
        })
        return _obj


