# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from tornclient.models.forum_thread_author import ForumThreadAuthor
from typing import Optional, Set
from typing_extensions import Self

class ForumThreadBase(BaseModel):
    """
    ForumThreadBase
    """ # noqa: E501
    id: StrictInt
    title: StrictStr
    forum_id: StrictInt
    posts: StrictInt
    rating: StrictInt
    views: StrictInt = Field(description="Total number of times players have opened this thread.")
    author: ForumThreadAuthor
    last_poster: Optional[ForumThreadAuthor]
    first_post_time: StrictInt
    last_post_time: Optional[StrictInt]
    has_poll: StrictBool
    is_locked: StrictBool
    is_sticky: StrictBool
    __properties: ClassVar[List[str]] = ["id", "title", "forum_id", "posts", "rating", "views", "author", "last_poster", "first_post_time", "last_post_time", "has_poll", "is_locked", "is_sticky"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ForumThreadBase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of author
        if self.author:
            _dict['author'] = self.author.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_poster
        if self.last_poster:
            _dict['last_poster'] = self.last_poster.to_dict()
        # set to None if last_poster (nullable) is None
        # and model_fields_set contains the field
        if self.last_poster is None and "last_poster" in self.model_fields_set:
            _dict['last_poster'] = None

        # set to None if last_post_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_post_time is None and "last_post_time" in self.model_fields_set:
            _dict['last_post_time'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ForumThreadBase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "forum_id": obj.get("forum_id"),
            "posts": obj.get("posts"),
            "rating": obj.get("rating"),
            "views": obj.get("views"),
            "author": ForumThreadAuthor.from_dict(obj["author"]) if obj.get("author") is not None else None,
            "last_poster": ForumThreadAuthor.from_dict(obj["last_poster"]) if obj.get("last_poster") is not None else None,
            "first_post_time": obj.get("first_post_time"),
            "last_post_time": obj.get("last_post_time"),
            "has_poll": obj.get("has_poll"),
            "is_locked": obj.get("is_locked"),
            "is_sticky": obj.get("is_sticky")
        })
        return _obj


