# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from tornclient.models.forum_thread_author import ForumThreadAuthor
from typing import Optional, Set
from typing_extensions import Self

class ForumPost(BaseModel):
    """
    ForumPost
    """ # noqa: E501
    id: StrictInt
    thread_id: StrictInt
    author: ForumThreadAuthor
    is_legacy: StrictBool = Field(description="Indicates whether post was made using the old formatting engine which doesn't use HTML.")
    is_topic: StrictBool
    is_edited: StrictBool
    is_pinned: StrictBool
    created_time: StrictInt
    edited_by: StrictInt
    has_quote: StrictBool
    quoted_post_id: Optional[StrictInt]
    content: StrictStr = Field(description="depending on the input 'cat' parameter, this will either return raw value (with HTML) or plain text. Legacy posts are returned as is, they can't be stripped of tags.")
    likes: StrictInt
    dislikes: StrictInt
    __properties: ClassVar[List[str]] = ["id", "thread_id", "author", "is_legacy", "is_topic", "is_edited", "is_pinned", "created_time", "edited_by", "has_quote", "quoted_post_id", "content", "likes", "dislikes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ForumPost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of author
        if self.author:
            _dict['author'] = self.author.to_dict()
        # set to None if quoted_post_id (nullable) is None
        # and model_fields_set contains the field
        if self.quoted_post_id is None and "quoted_post_id" in self.model_fields_set:
            _dict['quoted_post_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ForumPost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "thread_id": obj.get("thread_id"),
            "author": ForumThreadAuthor.from_dict(obj["author"]) if obj.get("author") is not None else None,
            "is_legacy": obj.get("is_legacy"),
            "is_topic": obj.get("is_topic"),
            "is_edited": obj.get("is_edited"),
            "is_pinned": obj.get("is_pinned"),
            "created_time": obj.get("created_time"),
            "edited_by": obj.get("edited_by"),
            "has_quote": obj.get("has_quote"),
            "quoted_post_id": obj.get("quoted_post_id"),
            "content": obj.get("content"),
            "likes": obj.get("likes"),
            "dislikes": obj.get("dislikes")
        })
        return _obj


