# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from tornclient.models.personal_stats_crimes_v1 import PersonalStatsCrimesV1
from tornclient.models.personal_stats_crimes_v2 import PersonalStatsCrimesV2
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

PERSONALSTATSCRIMESCRIMES_ONE_OF_SCHEMAS = ["PersonalStatsCrimesV1", "PersonalStatsCrimesV2"]

class PersonalStatsCrimesCrimes(BaseModel):
    """
    PersonalStatsCrimesCrimes
    """
    # data type: PersonalStatsCrimesV1
    oneof_schema_1_validator: Optional[PersonalStatsCrimesV1] = None
    # data type: PersonalStatsCrimesV2
    oneof_schema_2_validator: Optional[PersonalStatsCrimesV2] = None
    actual_instance: Optional[Union[PersonalStatsCrimesV1, PersonalStatsCrimesV2]] = None
    one_of_schemas: Set[str] = { "PersonalStatsCrimesV1", "PersonalStatsCrimesV2" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = PersonalStatsCrimesCrimes.model_construct()
        error_messages = []
        match = 0
        # validate data type: PersonalStatsCrimesV1
        if not isinstance(v, PersonalStatsCrimesV1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PersonalStatsCrimesV1`")
        else:
            match += 1
        # validate data type: PersonalStatsCrimesV2
        if not isinstance(v, PersonalStatsCrimesV2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PersonalStatsCrimesV2`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in PersonalStatsCrimesCrimes with oneOf schemas: PersonalStatsCrimesV1, PersonalStatsCrimesV2. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in PersonalStatsCrimesCrimes with oneOf schemas: PersonalStatsCrimesV1, PersonalStatsCrimesV2. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into PersonalStatsCrimesV1
        try:
            instance.actual_instance = PersonalStatsCrimesV1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PersonalStatsCrimesV2
        try:
            instance.actual_instance = PersonalStatsCrimesV2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into PersonalStatsCrimesCrimes with oneOf schemas: PersonalStatsCrimesV1, PersonalStatsCrimesV2. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PersonalStatsCrimesCrimes with oneOf schemas: PersonalStatsCrimesV1, PersonalStatsCrimesV2. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], PersonalStatsCrimesV1, PersonalStatsCrimesV2]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


