# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from tornclient.models.racing_car_upgrades_response import RacingCarUpgradesResponse
from tornclient.models.racing_cars_response import RacingCarsResponse
from tornclient.models.racing_lookup_response import RacingLookupResponse
from tornclient.models.racing_race_details_response import RacingRaceDetailsResponse
from tornclient.models.racing_races_response import RacingRacesResponse
from tornclient.models.racing_track_records_response import RacingTrackRecordsResponse
from tornclient.models.racing_tracks_response import RacingTracksResponse
from tornclient.models.timestamp_response import TimestampResponse
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

RACINGGET200RESPONSE_ANY_OF_SCHEMAS = ["RacingCarUpgradesResponse", "RacingCarsResponse", "RacingLookupResponse", "RacingRaceDetailsResponse", "RacingRacesResponse", "RacingTrackRecordsResponse", "RacingTracksResponse", "TimestampResponse"]

class RacingGet200Response(BaseModel):
    """
    RacingGet200Response
    """

    # data type: RacingRacesResponse
    anyof_schema_1_validator: Optional[RacingRacesResponse] = None
    # data type: RacingTrackRecordsResponse
    anyof_schema_2_validator: Optional[RacingTrackRecordsResponse] = None
    # data type: RacingRaceDetailsResponse
    anyof_schema_3_validator: Optional[RacingRaceDetailsResponse] = None
    # data type: RacingCarsResponse
    anyof_schema_4_validator: Optional[RacingCarsResponse] = None
    # data type: RacingTracksResponse
    anyof_schema_5_validator: Optional[RacingTracksResponse] = None
    # data type: RacingCarUpgradesResponse
    anyof_schema_6_validator: Optional[RacingCarUpgradesResponse] = None
    # data type: RacingLookupResponse
    anyof_schema_7_validator: Optional[RacingLookupResponse] = None
    # data type: TimestampResponse
    anyof_schema_8_validator: Optional[TimestampResponse] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[RacingCarUpgradesResponse, RacingCarsResponse, RacingLookupResponse, RacingRaceDetailsResponse, RacingRacesResponse, RacingTrackRecordsResponse, RacingTracksResponse, TimestampResponse]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "RacingCarUpgradesResponse", "RacingCarsResponse", "RacingLookupResponse", "RacingRaceDetailsResponse", "RacingRacesResponse", "RacingTrackRecordsResponse", "RacingTracksResponse", "TimestampResponse" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = RacingGet200Response.model_construct()
        error_messages = []
        # validate data type: RacingRacesResponse
        if not isinstance(v, RacingRacesResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RacingRacesResponse`")
        else:
            return v

        # validate data type: RacingTrackRecordsResponse
        if not isinstance(v, RacingTrackRecordsResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RacingTrackRecordsResponse`")
        else:
            return v

        # validate data type: RacingRaceDetailsResponse
        if not isinstance(v, RacingRaceDetailsResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RacingRaceDetailsResponse`")
        else:
            return v

        # validate data type: RacingCarsResponse
        if not isinstance(v, RacingCarsResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RacingCarsResponse`")
        else:
            return v

        # validate data type: RacingTracksResponse
        if not isinstance(v, RacingTracksResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RacingTracksResponse`")
        else:
            return v

        # validate data type: RacingCarUpgradesResponse
        if not isinstance(v, RacingCarUpgradesResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RacingCarUpgradesResponse`")
        else:
            return v

        # validate data type: RacingLookupResponse
        if not isinstance(v, RacingLookupResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RacingLookupResponse`")
        else:
            return v

        # validate data type: TimestampResponse
        if not isinstance(v, TimestampResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TimestampResponse`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in RacingGet200Response with anyOf schemas: RacingCarUpgradesResponse, RacingCarsResponse, RacingLookupResponse, RacingRaceDetailsResponse, RacingRacesResponse, RacingTrackRecordsResponse, RacingTracksResponse, TimestampResponse. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[RacingRacesResponse] = None
        try:
            instance.actual_instance = RacingRacesResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[RacingTrackRecordsResponse] = None
        try:
            instance.actual_instance = RacingTrackRecordsResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[RacingRaceDetailsResponse] = None
        try:
            instance.actual_instance = RacingRaceDetailsResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[RacingCarsResponse] = None
        try:
            instance.actual_instance = RacingCarsResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[RacingTracksResponse] = None
        try:
            instance.actual_instance = RacingTracksResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_6_validator: Optional[RacingCarUpgradesResponse] = None
        try:
            instance.actual_instance = RacingCarUpgradesResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_7_validator: Optional[RacingLookupResponse] = None
        try:
            instance.actual_instance = RacingLookupResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_8_validator: Optional[TimestampResponse] = None
        try:
            instance.actual_instance = TimestampResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into RacingGet200Response with anyOf schemas: RacingCarUpgradesResponse, RacingCarsResponse, RacingLookupResponse, RacingRaceDetailsResponse, RacingRacesResponse, RacingTrackRecordsResponse, RacingTracksResponse, TimestampResponse. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], RacingCarUpgradesResponse, RacingCarsResponse, RacingLookupResponse, RacingRaceDetailsResponse, RacingRacesResponse, RacingTrackRecordsResponse, RacingTracksResponse, TimestampResponse]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


