# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from tornclient.models.user_personal_stats_category import UserPersonalStatsCategory
from tornclient.models.user_personal_stats_full import UserPersonalStatsFull
from tornclient.models.user_personal_stats_full_public import UserPersonalStatsFullPublic
from tornclient.models.user_personal_stats_historic import UserPersonalStatsHistoric
from tornclient.models.user_personal_stats_popular import UserPersonalStatsPopular
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

USERPERSONALSTATSRESPONSE_ONE_OF_SCHEMAS = ["UserPersonalStatsCategory", "UserPersonalStatsFull", "UserPersonalStatsFullPublic", "UserPersonalStatsHistoric", "UserPersonalStatsPopular"]

class UserPersonalStatsResponse(BaseModel):
    """
    UserPersonalStatsResponse
    """
    # data type: UserPersonalStatsFull
    oneof_schema_1_validator: Optional[UserPersonalStatsFull] = None
    # data type: UserPersonalStatsFullPublic
    oneof_schema_2_validator: Optional[UserPersonalStatsFullPublic] = None
    # data type: UserPersonalStatsCategory
    oneof_schema_3_validator: Optional[UserPersonalStatsCategory] = None
    # data type: UserPersonalStatsPopular
    oneof_schema_4_validator: Optional[UserPersonalStatsPopular] = None
    # data type: UserPersonalStatsHistoric
    oneof_schema_5_validator: Optional[UserPersonalStatsHistoric] = None
    actual_instance: Optional[Union[UserPersonalStatsCategory, UserPersonalStatsFull, UserPersonalStatsFullPublic, UserPersonalStatsHistoric, UserPersonalStatsPopular]] = None
    one_of_schemas: Set[str] = { "UserPersonalStatsCategory", "UserPersonalStatsFull", "UserPersonalStatsFullPublic", "UserPersonalStatsHistoric", "UserPersonalStatsPopular" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = UserPersonalStatsResponse.model_construct()
        error_messages = []
        match = 0
        # validate data type: UserPersonalStatsFull
        if not isinstance(v, UserPersonalStatsFull):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserPersonalStatsFull`")
        else:
            match += 1
        # validate data type: UserPersonalStatsFullPublic
        if not isinstance(v, UserPersonalStatsFullPublic):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserPersonalStatsFullPublic`")
        else:
            match += 1
        # validate data type: UserPersonalStatsCategory
        if not isinstance(v, UserPersonalStatsCategory):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserPersonalStatsCategory`")
        else:
            match += 1
        # validate data type: UserPersonalStatsPopular
        if not isinstance(v, UserPersonalStatsPopular):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserPersonalStatsPopular`")
        else:
            match += 1
        # validate data type: UserPersonalStatsHistoric
        if not isinstance(v, UserPersonalStatsHistoric):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserPersonalStatsHistoric`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in UserPersonalStatsResponse with oneOf schemas: UserPersonalStatsCategory, UserPersonalStatsFull, UserPersonalStatsFullPublic, UserPersonalStatsHistoric, UserPersonalStatsPopular. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in UserPersonalStatsResponse with oneOf schemas: UserPersonalStatsCategory, UserPersonalStatsFull, UserPersonalStatsFullPublic, UserPersonalStatsHistoric, UserPersonalStatsPopular. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into UserPersonalStatsFull
        try:
            instance.actual_instance = UserPersonalStatsFull.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserPersonalStatsFullPublic
        try:
            instance.actual_instance = UserPersonalStatsFullPublic.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserPersonalStatsCategory
        try:
            instance.actual_instance = UserPersonalStatsCategory.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserPersonalStatsPopular
        try:
            instance.actual_instance = UserPersonalStatsPopular.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserPersonalStatsHistoric
        try:
            instance.actual_instance = UserPersonalStatsHistoric.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into UserPersonalStatsResponse with oneOf schemas: UserPersonalStatsCategory, UserPersonalStatsFull, UserPersonalStatsFullPublic, UserPersonalStatsHistoric, UserPersonalStatsPopular. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into UserPersonalStatsResponse with oneOf schemas: UserPersonalStatsCategory, UserPersonalStatsFull, UserPersonalStatsFullPublic, UserPersonalStatsHistoric, UserPersonalStatsPopular. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], UserPersonalStatsCategory, UserPersonalStatsFull, UserPersonalStatsFullPublic, UserPersonalStatsHistoric, UserPersonalStatsPopular]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


