# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from tornclient.models.user_crime_details_bootlegging import UserCrimeDetailsBootlegging
from tornclient.models.user_crime_details_card_skimming import UserCrimeDetailsCardSkimming
from tornclient.models.user_crime_details_cracking import UserCrimeDetailsCracking
from tornclient.models.user_crime_details_graffiti import UserCrimeDetailsGraffiti
from tornclient.models.user_crime_details_hustling import UserCrimeDetailsHustling
from tornclient.models.user_crime_details_scamming import UserCrimeDetailsScamming
from tornclient.models.user_crime_details_shoplifting import UserCrimeDetailsShoplifting
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

USERCRIMEMISCELLANEOUS_ONE_OF_SCHEMAS = ["UserCrimeDetailsBootlegging", "UserCrimeDetailsCardSkimming", "UserCrimeDetailsCracking", "UserCrimeDetailsGraffiti", "UserCrimeDetailsHustling", "UserCrimeDetailsScamming", "UserCrimeDetailsShoplifting"]

class UserCrimeMiscellaneous(BaseModel):
    """
     Miscellaneous stats for specific crime. Results differ based on the cat id.
    """
    # data type: UserCrimeDetailsBootlegging
    oneof_schema_1_validator: Optional[UserCrimeDetailsBootlegging] = None
    # data type: UserCrimeDetailsGraffiti
    oneof_schema_2_validator: Optional[UserCrimeDetailsGraffiti] = None
    # data type: UserCrimeDetailsShoplifting
    oneof_schema_3_validator: Optional[UserCrimeDetailsShoplifting] = None
    # data type: UserCrimeDetailsCardSkimming
    oneof_schema_4_validator: Optional[UserCrimeDetailsCardSkimming] = None
    # data type: UserCrimeDetailsHustling
    oneof_schema_5_validator: Optional[UserCrimeDetailsHustling] = None
    # data type: UserCrimeDetailsCracking
    oneof_schema_6_validator: Optional[UserCrimeDetailsCracking] = None
    # data type: UserCrimeDetailsScamming
    oneof_schema_7_validator: Optional[UserCrimeDetailsScamming] = None
    actual_instance: Optional[Union[UserCrimeDetailsBootlegging, UserCrimeDetailsCardSkimming, UserCrimeDetailsCracking, UserCrimeDetailsGraffiti, UserCrimeDetailsHustling, UserCrimeDetailsScamming, UserCrimeDetailsShoplifting]] = None
    one_of_schemas: Set[str] = { "UserCrimeDetailsBootlegging", "UserCrimeDetailsCardSkimming", "UserCrimeDetailsCracking", "UserCrimeDetailsGraffiti", "UserCrimeDetailsHustling", "UserCrimeDetailsScamming", "UserCrimeDetailsShoplifting" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        if v is None:
            return v

        instance = UserCrimeMiscellaneous.model_construct()
        error_messages = []
        match = 0
        # validate data type: UserCrimeDetailsBootlegging
        if not isinstance(v, UserCrimeDetailsBootlegging):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserCrimeDetailsBootlegging`")
        else:
            match += 1
        # validate data type: UserCrimeDetailsGraffiti
        if not isinstance(v, UserCrimeDetailsGraffiti):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserCrimeDetailsGraffiti`")
        else:
            match += 1
        # validate data type: UserCrimeDetailsShoplifting
        if not isinstance(v, UserCrimeDetailsShoplifting):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserCrimeDetailsShoplifting`")
        else:
            match += 1
        # validate data type: UserCrimeDetailsCardSkimming
        if not isinstance(v, UserCrimeDetailsCardSkimming):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserCrimeDetailsCardSkimming`")
        else:
            match += 1
        # validate data type: UserCrimeDetailsHustling
        if not isinstance(v, UserCrimeDetailsHustling):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserCrimeDetailsHustling`")
        else:
            match += 1
        # validate data type: UserCrimeDetailsCracking
        if not isinstance(v, UserCrimeDetailsCracking):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserCrimeDetailsCracking`")
        else:
            match += 1
        # validate data type: UserCrimeDetailsScamming
        if not isinstance(v, UserCrimeDetailsScamming):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserCrimeDetailsScamming`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in UserCrimeMiscellaneous with oneOf schemas: UserCrimeDetailsBootlegging, UserCrimeDetailsCardSkimming, UserCrimeDetailsCracking, UserCrimeDetailsGraffiti, UserCrimeDetailsHustling, UserCrimeDetailsScamming, UserCrimeDetailsShoplifting. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in UserCrimeMiscellaneous with oneOf schemas: UserCrimeDetailsBootlegging, UserCrimeDetailsCardSkimming, UserCrimeDetailsCracking, UserCrimeDetailsGraffiti, UserCrimeDetailsHustling, UserCrimeDetailsScamming, UserCrimeDetailsShoplifting. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: Optional[str]) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        if json_str is None:
            return instance

        error_messages = []
        match = 0

        # deserialize data into UserCrimeDetailsBootlegging
        try:
            instance.actual_instance = UserCrimeDetailsBootlegging.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserCrimeDetailsGraffiti
        try:
            instance.actual_instance = UserCrimeDetailsGraffiti.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserCrimeDetailsShoplifting
        try:
            instance.actual_instance = UserCrimeDetailsShoplifting.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserCrimeDetailsCardSkimming
        try:
            instance.actual_instance = UserCrimeDetailsCardSkimming.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserCrimeDetailsHustling
        try:
            instance.actual_instance = UserCrimeDetailsHustling.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserCrimeDetailsCracking
        try:
            instance.actual_instance = UserCrimeDetailsCracking.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserCrimeDetailsScamming
        try:
            instance.actual_instance = UserCrimeDetailsScamming.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into UserCrimeMiscellaneous with oneOf schemas: UserCrimeDetailsBootlegging, UserCrimeDetailsCardSkimming, UserCrimeDetailsCracking, UserCrimeDetailsGraffiti, UserCrimeDetailsHustling, UserCrimeDetailsScamming, UserCrimeDetailsShoplifting. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into UserCrimeMiscellaneous with oneOf schemas: UserCrimeDetailsBootlegging, UserCrimeDetailsCardSkimming, UserCrimeDetailsCracking, UserCrimeDetailsGraffiti, UserCrimeDetailsHustling, UserCrimeDetailsScamming, UserCrimeDetailsShoplifting. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], UserCrimeDetailsBootlegging, UserCrimeDetailsCardSkimming, UserCrimeDetailsCracking, UserCrimeDetailsGraffiti, UserCrimeDetailsHustling, UserCrimeDetailsScamming, UserCrimeDetailsShoplifting]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


