# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from tornclient.models.user_crime_attempts import UserCrimeAttempts
from tornclient.models.user_crime_miscellaneous import UserCrimeMiscellaneous
from tornclient.models.user_crime_rewards import UserCrimeRewards
from tornclient.models.user_crime_uniques import UserCrimeUniques
from typing import Optional, Set
from typing_extensions import Self

class UserCrime(BaseModel):
    """
    UserCrime
    """ # noqa: E501
    nerve_spent: StrictInt
    skill: StrictInt
    progression_bonus: StrictInt
    rewards: UserCrimeRewards
    attempts: UserCrimeAttempts
    uniques: List[UserCrimeUniques]
    miscellaneous: Optional[UserCrimeMiscellaneous]
    __properties: ClassVar[List[str]] = ["nerve_spent", "skill", "progression_bonus", "rewards", "attempts", "uniques", "miscellaneous"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserCrime from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of rewards
        if self.rewards:
            _dict['rewards'] = self.rewards.to_dict()
        # override the default output from pydantic by calling `to_dict()` of attempts
        if self.attempts:
            _dict['attempts'] = self.attempts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in uniques (list)
        _items = []
        if self.uniques:
            for _item_uniques in self.uniques:
                if _item_uniques:
                    _items.append(_item_uniques.to_dict())
            _dict['uniques'] = _items
        # override the default output from pydantic by calling `to_dict()` of miscellaneous
        if self.miscellaneous:
            _dict['miscellaneous'] = self.miscellaneous.to_dict()
        # set to None if miscellaneous (nullable) is None
        # and model_fields_set contains the field
        if self.miscellaneous is None and "miscellaneous" in self.model_fields_set:
            _dict['miscellaneous'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserCrime from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nerve_spent": obj.get("nerve_spent"),
            "skill": obj.get("skill"),
            "progression_bonus": obj.get("progression_bonus"),
            "rewards": UserCrimeRewards.from_dict(obj["rewards"]) if obj.get("rewards") is not None else None,
            "attempts": UserCrimeAttempts.from_dict(obj["attempts"]) if obj.get("attempts") is not None else None,
            "uniques": [UserCrimeUniques.from_dict(_item) for _item in obj["uniques"]] if obj.get("uniques") is not None else None,
            "miscellaneous": UserCrimeMiscellaneous.from_dict(obj["miscellaneous"]) if obj.get("miscellaneous") is not None else None
        })
        return _obj


