# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WeaponBonusEnum(str, Enum):
    """
    WeaponBonusEnum
    """

    """
    allowed enum values
    """
    ANY = 'Any'
    DOUBLE = 'Double'
    YELLOW = 'Yellow'
    ORANGE = 'Orange'
    RED = 'Red'
    ACHILLES = 'Achilles'
    ASSASSINATE = 'Assassinate'
    BACKSTAB = 'Backstab'
    BERSERK = 'Berserk'
    BLEED = 'Bleed'
    BLINDFIRE = 'Blindfire'
    BLINDSIDE = 'Blindside'
    BLOODLUST = 'Bloodlust'
    BURN = 'Burn'
    COMEBACK = 'Comeback'
    CONSERVE = 'Conserve'
    CRIPPLE = 'Cripple'
    CRUSHER = 'Crusher'
    CUPID = 'Cupid'
    DEADEYE = 'Deadeye'
    DEADLY = 'Deadly'
    DEMORALIZE = 'Demoralize'
    DISARM = 'Disarm'
    DOUBLE_MINUS_EDGED = 'Double-edged'
    DOUBLE_TAP = 'Double Tap'
    EMASCULATE = 'Emasculate'
    EMPOWER = 'Empower'
    EVISCERATE = 'Eviscerate'
    EXECUTE = 'Execute'
    EXPOSE = 'Expose'
    FINALE = 'Finale'
    FOCUS = 'Focus'
    FREEZE = 'Freeze'
    FRENZY = 'Frenzy'
    FURY = 'Fury'
    GRACE = 'Grace'
    HAZARDOUS = 'Hazardous'
    HOME_RUN = 'Home run'
    IRRADIATE = 'Irradiate'
    LACERATE = 'Lacerate'
    MOTIVATION = 'Motivation'
    PARALYZE = 'Paralyze'
    PARRY = 'Parry'
    PENETRATE = 'Penetrate'
    PLUNDER = 'Plunder'
    POISON = 'Poison'
    POWERFUL = 'Powerful'
    PROFICIENCE = 'Proficience'
    PUNCTURE = 'Puncture'
    QUICKEN = 'Quicken'
    RAGE = 'Rage'
    REVITALIZE = 'Revitalize'
    ROSHAMBO = 'Roshambo'
    SHOCK = 'Shock'
    SLEEP = 'Sleep'
    SLOW = 'Slow'
    SMASH = 'Smash'
    SMURF = 'Smurf'
    SPECIALIST = 'Specialist'
    SPRAY = 'Spray'
    STORAGE = 'Storage'
    STRICKEN = 'Stricken'
    STUN = 'Stun'
    SUPPRESS = 'Suppress'
    SURE_SHOT = 'Sure Shot'
    THROTTLE = 'Throttle'
    TOXIN = 'Toxin'
    WARLORD = 'Warlord'
    WEAKEN = 'Weaken'
    WIND_MINUS_UP = 'Wind-up'
    WITHER = 'Wither'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WeaponBonusEnum from a JSON string"""
        return cls(json.loads(json_str))


